Repository NitramMann21/JTA, pull requests merged in 2021-07, with the labels that each got.

#1 Updated README
  README.md
Labels: documentation

#2 First pass on clips
  src/main/java/de/arnomann/martin/jta/api/JTABot.java
  src/main/java/de/arnomann/martin/jta/api/entities/Clip.java
  src/main/java/de/arnomann/martin/jta/internal/JTABotImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/ClipImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/MessageSenderBot.java
  src/test/java/JTATest.java
Labels: documentation, enhancement

#4 Add user and channel management
  .tutorials/HOW_TO_GET_USER_ACCESS_TOKENS.md
  src/main/java/de/arnomann/martin/jta/api/JTABot.java
  src/main/java/de/arnomann/martin/jta/api/entities/Channel.java
  src/main/java/de/arnomann/martin/jta/internal/JTABotImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/ChannelImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/HypeTrainImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/StreamImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/StreamScheduleImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/TeamImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/UserImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/VideoImpl.java
  src/test/java/JTATest.java
Labels: enhancement

#6 Add video management methods
  src/main/java/de/arnomann/martin/jta/api/entities/Video.java
  src/main/java/de/arnomann/martin/jta/internal/entities/ChannelImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/VideoImpl.java
  src/main/java/de/arnomann/martin/jta/internal/requests/Requester.java
  src/test/java/JTATest.java
Labels: documentation, enhancement

#7 Add ads
  src/main/java/de/arnomann/martin/jta/api/AdLength.java
  src/main/java/de/arnomann/martin/jta/api/entities/Stream.java
  src/main/java/de/arnomann/martin/jta/internal/JTABotImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/ChannelImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/HypeTrainImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/StreamImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/StreamScheduleImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/TeamImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/UserImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/VideoImpl.java
  src/main/java/de/arnomann/martin/jta/internal/requests/Requester.java
Labels: documentation, enhancement

#8 Add moderation methods
  src/main/java/de/arnomann/martin/jta/api/entities/Channel.java
  src/main/java/de/arnomann/martin/jta/internal/entities/ChannelImpl.java
Labels: documentation, enhancement

#9 Add follow and block getters
  src/main/java/de/arnomann/martin/jta/api/entities/User.java
  src/main/java/de/arnomann/martin/jta/internal/entities/ChannelImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/UserImpl.java
Labels: documentation, enhancement

#5 Release 2.0.0 - User/Channel Management
  .tutorials/HOW_TO_GET_USER_ACCESS_TOKENS.md
  pom.xml
  src/main/java/de/arnomann/martin/jta/api/AdLength.java
  src/main/java/de/arnomann/martin/jta/api/JTABot.java
  src/main/java/de/arnomann/martin/jta/api/entities/Channel.java
  src/main/java/de/arnomann/martin/jta/api/entities/Stream.java
  src/main/java/de/arnomann/martin/jta/api/entities/User.java
  src/main/java/de/arnomann/martin/jta/api/entities/Video.java
  src/main/java/de/arnomann/martin/jta/internal/JTABotImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/ChannelImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/HypeTrainImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/StreamImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/StreamScheduleImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/TeamImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/UserImpl.java
  src/main/java/de/arnomann/martin/jta/internal/entities/VideoImpl.java
  src/main/java/de/arnomann/martin/jta/internal/requests/Requester.java
  src/test/java/JTATest.java
Labels: documentation, enhancement, milestone
